config/routes.rb
Starterpad::Application.routes.draw do
  
  ActiveAdmin.routes(self)
  # Devise
  devise_for :users, :controllers => { :registrations => "user/registrations", confirmations: 'user/confirmations', sessions: 'user/sessions' }

  resources :notifications
  resources :conversations, :only => [:index, :create, :show, :update] do
    member do
      get :hide
    end
  end
  resources :private_messages

  # CakePHP Redirections
  get 'group/:id', to: redirect('/groups/%{id}')
  get 'startups/index', to: redirect('/startups')
  get 'startup/:id', to: redirect('/startups/%{id}')  
  get 'startups/index/keywords:(:market_id)', to: redirect { |path_params, req| "/startups/markets/#{path_params[:market_id].to_url}" }, :constraints => { :market_id => /[^\/]+/ }
  get 'starters/skill:(:keyword_id)', to: redirect { |path_params, req| "/starters/skill/#{path_params[:keyword_id].to_url}" }, :constraints => { :keyword_id => /[^\/]+/ }
  get 'starters/role:(:role_id)', to: redirect { |path_params, req| "/starters/role/#{path_params[:role_id].to_url}" }
  get 'users/view/:id/page:page_id', to: redirect { |path_params, req| 
    path_params[:page_id][0] = '' if path_params[:page_id]
    path_params[:page_id] = 'friends' if path_params[:page_id] == 'connections'
    "/#{path_params[:id]}/#{path_params[:page_id]}" 
  }
  get 'pages/display/privacy', to: redirect('/privacy')


  resources :startups, :controller => 'startups' do
    collection do
      get :my_startups
      get :following_startups
      get 'pages/:page' => :index
      get 'markets/:market_id(/:page)' => :by_market, :as => :market
      post 'country'
      get 'country(/:title(/:page))' => "startups#country", :as => :get_by_country
      get 'country_auto_complete'
      post 'city'
      get 'city(/:name(/:page))' =>  "startups#city", :as => :get_by_city
      get 'city_auto_complete'
      get 'autocomplete'
    end
    resources :posts, only: [:create, :destroy, :index], controller: 'startup_posts'
    member do
      post :follow
      post :unfollow
    end
  end
  resources :starters, :controller => 'users', :only => [:index] do
    collection do
      get 'pages/:page' => :index
      get 'role/:role_id(/:page)' => :by_role, :as => :role
      get 'skill/:keyword_id(/:page)' => :by_keyword, :as => :skill
      post 'country'
      get 'country(/:title(/:page))' => "users#country", :as => :get_by_country
      get 'country_auto_complete'
      post 'city'
      get 'city(/:name(/:page))' => "users#city", :as => :get_by_city
      get 'city_auto_complete'
    end
  end
  resources :groups do
    member do
      post 'join/:user_id' => :join, :as => :join
      delete 'leave/:user_id' => :leave, :as => :leave
      post 'suggest_to_friend' => :suggest_to_friend, :as => :suggest_to_friend
    end
    resources :posts, only: [:create, :destroy, :index], controller: 'group_posts'
    collection do
      get 'autocomplete'
      get 'pages/:page' => :index
      get 'my_groups(/pages/:page)' => :my_groups, :as => :my
      get 'my_moderated_groups(/pages/:page)' => :my_moderated_groups, :as => :my_moderated
    end
  end
  resources :posts, :except => [:index] do
    collection do
      get 'pages/:page' => :index
    end
    resources :comments, :only => [:create, :index, :destroy]
    resources :likes, :only => [:index, :create, :destroy]
  end

  resources :users, only: [:update] do
    collection do
      get 'step/:step' => :wizard, :as => :wizard
      put :ping
    end
    resources :friends, :controller => 'user/friendships', :only => [:create, :destroy] do
      member do
        delete :cancel
        put :accept
      end
    end
    collection do
      get :friends, :to => 'user/friendships', :format => :json
    end
    member do
      match :update_settings , :to => 'users#update_settings', :via => [:patch]
    end
    resource :followerships, :controller => 'user/followerships', :only => [:create, :destroy]
  end

  resources :contact, :only => [:index, :create]
  
  authenticated :user do
    get '/', :to => "pages#pad"
  end
  
  devise_scope :user do
    get '/', :to => 'pages#home'
  end

  root :to => 'pages#home'

  # OAuth
  get 'auth/:provider/disconnect', to: 'sessions#disconnect'
  get 'auth/:provider/callback', to: 'sessions#connect'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'facebook_disconnect', to: 'user_facebooks#facebook_disconnect', as: 'facebook_disconnect'
  get 'twitter_disconnect', to: 'user_twitters#twitter_disconnect', as: 'twitter_disconnect'

  # Pages
  get '/badges' => 'pages#badges'
  get '/privacy' => 'pages#privacy'
  get '/terms' => 'pages#terms'

  # Users
  get 'profile', :to => 'users#profile', :as => 'my_profile'
  get 'profile/details',  to: 'users#profile_details', :as => 'my_profile_details'
  get 'profile/change_password',  to: 'users#change_password', :as => 'change_password'
  get 'profile/email_settings',  to: 'users#email_settings', :as => 'email_settings'
  get 'profile/social_network_settings', to: 'users#social_network_settings', as: 'social_network_settings'
  match 'profile/email_addresses', to: 'users#email_addresses', as: :user_email_addresses, via: [:get, :post]
  match 'profile/twitter_update_settings', to: 'users#twitter_update_settings', as: 'twitter_update_settings', via: [:get, :patch]

  get '/user_online_ping',  to: 'users#online_ping', :as => 'user_online_ping'
  get '/sign_action',  to: 'users#sign_action', :as => 'sign_action'
  match 'deactivate_account', to: 'users#deactivate_account', via: [:get, :post], as: 'deactivate_account'  
  match 'resend_confirmation', to: 'users#resend_confirmation', via: [:post], as: 'resend_confirmation'  
  # Conversations
  get '/inbox' => 'conversations#index'

  # Keywords
  resources :keywords, only: [:index]

  # Friends
  get '/contacts' => 'user/friendships#my_friends', :as => "my_friends"

  # Cronjobs
  get '/cronjobs/begin' => 'cronjobs#begin'
  
  # at the moment commenting out this routes, there are no sign of this usage.
  # get '/follow_startup/:id',  to: 'startup_followers#create', :as => "follow_startup"
  get '/startup_followers/:id',  to: 'followers#index', :as => "startup_followers"
   
  get ':url/friends(/page/:page)', :to => 'user/friendships#index', :as =>'friends'
  get ':url/followers(/page/:page)', :to => 'user/followerships#index', :as =>'followers'
  get ':url/followings(/page/:page)', :to => 'user/followerships#followings', :as =>'followings'

  # For Deployment
  # post 'deploy/T5ns7Pqv3G6' => 'deployments#deploy'

  # Test
  match 'test', via: :get, to: lambda {|id| 
    html = 'test'
    [200, {'Content-Type' => 'text/plain'} , [html]] 
  }

  # DISCUSS
  
  resources :items, path: 'discuss', except: [:destroy] do
    
    resources :item_comments

    collection do
      get :newest, to: 'items#newest'
    end
    member do      
      post :toggle
      post :vote, to: 'user_item_votes#create'
      delete :vote, to: 'user_item_votes#destroy'
    end
  end

  # Show User (Always the last one)
  get ':url', :to => 'users#show', :as =>'profile', constraints: ActiveUserConstraint

end

app/models/user/facebook_auth.rb
# == Schema Information
#
# Table name: user_facebooks
#
#  id           :integer
#  user_id      :integer
#  title        :string(500)
#  email        :string(500)
#  facebook_id  :integer
#  access_token :string(500)
#  hash         :string(500)
#  last_login   :datetime
#

class User::FacebookAuth < ActiveRecord::Base

  self.table_name = "user_facebooks"
  self.primary_key = :id
  belongs_to :user

end

app/models/user/role.rb
# == Schema Information
#
# Table name: user_roles
#
#  id     :integer          not null, primary key
#  title  :string(500)
#  slug   :string(500)
#  nb     :integer          default(0)
#  plural :string(500)
#

class User::Role < ActiveRecord::Base

  has_many :profiles, :foreign_key => 'user_role_id'
  
end

app/models/user/setting.rb
# == Schema Information
#
# Table name: email_settings
#
#  id               :integer          not null, primary key
#  user_id          :integer
#  private_messages :boolean
#  morning_mail     :boolean
#  last_email_at    :datetime
#  next_email_at    :datetime
#  emails_count     :integer
#  admin_emails     :integer
#  confirmed_emails :integer
#  welcome_emails   :integer
#  hash_code        :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#  google           :boolean
#  subscription     :boolean
#

class User::Setting < ActiveRecord::Base

  self.table_name = 'email_settings'
  self.primary_key = :id 
  belongs_to :user

	attr_accessible :google, :morning_mail, :private_messages, :subscription, :user_id, :discuss_trending, :startup_update_reminder

 	def subscription=(value)
 		super(value)
 		user = {
 			:email => self.user.email,
 			:ip => self.user.current_sign_in_ip,
 			:name => self.user.title
 		}
 		update_madmimi(user, self.subscription ) if self.subscription_changed?
 	end

  def discuss_trending=(value)
    super(value)
    user = {
      :email => self.user.email,
      :ip => self.user.current_sign_in_ip,
      :name => self.user.title
    }
    update_madmimi(user, self.discuss_trending, "Discuss - Trending Items" ) if self.discuss_trending_changed?
  end

 	protected

 	def update_madmimi(user,value,list="New Users")
 		mimi = MadMimi.new(Settings.madmimi.email, Settings.madmimi.key)
  	if value
  		user[:add_list] = list
  		mimi.add_user(user)
  	else
	  	mimi.remove_from_list(user[:email], list)
	  end
 	end
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?

    if resource.errors.empty?
      sign_in(resource)
      add_to_madmimi({ :email => resource.email, :name => resource.title, :ip => resource.current_sign_in_ip})
      add_to_sendy({ :email => resource.email, :name => resource.title})
      set_flash_message(:notice, :confirmed) if is_flashing_format?
      respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
    else
      respond_with_navigational(resource.errors, status: :unprocessable_entity){ render :new }
    end
    # sign_in(resource) if resource.errors.empty?
  end
end

app/controllers/user/followerships_controller.rb
class User::FollowershipsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :followings]
  before_action :is_active?, :except => [:index, :followings]
  respond_to :js

  def index
  	@user = User.find_by(:url => params[:url])
    raise ActionController::RoutingError.new('Not Found') if @user.nil?
  	@followers = @user.followers.active.page(params[:page]).per(20)
  end

  def followings
  	@user = User.find_by(:url => params[:url])
  	raise ActionController::RoutingError.new('Not Found') if @user.nil?
  	@followings = @user.followings.active.page(params[:page]).per(20)
  end

	# Follow
	def create
		@to_follow = User.active.find(params[:user_id]) #get the user
		@my_follower = current_user.followers.where(id: @to_follow.id) #check if the users follows me
		if @my_follower.present?
			current_user.followers.destroy(@my_follower)
			@friends = current_user.friends << @to_follow
			current_user.inverse_friends << @to_follow
			 Notification.create({
        user_id: current_user.id,
			  :recipient_id => @to_follow.id, 
			  :friendship_id => @friends.last.friendships.last.id,
			  :key_name => 'follows_back'
			})
		else
			# add notification
      @followingships = current_user.followingships.create(recipient_id: @to_follow.id)
      if @followingships.errors.empty? 
        @followings = current_user.followings
        Notification.create({
          user_id: current_user.id,
          :recipient_id => @to_follow.id, 
          :follower_id => @followingships.id,
          :key_name => 'user_follow'
        })		      
      else
        @errors = @followingships.errors.messages.map{|k,v| v.join('<br />')}

        ## If one of errors caused by inactive user, It will remove other errors messages 
        ## and only return error caused by inactive user 
        if @errors.find{ |e| e.include? I18n.t('.errors.messages.user_is_not_active') }
          @errors.select!{ |e| e.include? I18n.t('.errors.messages.user_is_not_active') }
        end
        render 'shared/add_error'
      end
		end
	end

	def destroy
		@to_unfollow = User.active.find(params[:user_id])
		current_user.followings.destroy(@to_unfollow)
	end

end

app/controllers/user/friendships_controller.rb
class User::FriendshipsController < ApplicationController  
  before_filter :authenticate_user!, :except => [:index]
  before_action :is_active?, :except => [:index, :friends, :my_friends]


  # Show user friends
  def index
    @user = User.find_by(:url => params[:url])
    raise ActionController::RoutingError.new('Not Found') if @user.nil?
    @friends = @user.friends.active.includes(:profile).page(params[:page]).per(20)
  end

  def friends
    @friends = current_user.friends.active.includes(:profile)
  end

  def my_friends
    # Get user_name
    @user = User.find_by_id(current_user.id)

    # Get friendships
    @friendships = Friendship.where(user_id: current_user.id, status: true).order('id desc')#.limit(10)

    friendships = @friendships.map(&:friend_id)

    # Get users
    @users = User.where(id: friendships).order('last_action_at desc')

    # received_friendships
    @received_friendships = Friendship.where(friend_id: current_user.id, status: false).order('id desc')

    # waiting friendships
    @waiting_friendships = Friendship.where(user_id: current_user.id, status: false).order('id desc')

    # Get Followers
    @followers = @user.followers.active

    # Get Followings
    @followings = @user.followings.active#.page(params[:page]).per(20)

    # mark as read notifications
    Notification.where("read is false and recipient_id = ? and key_name = 'friend_request'", current_user.id).update_all(:read => true)

    # nil news sync
    session[:new_sync_at] = nil
  end

  # create a friendship
  def create
    @user = User.find(params[:user_id])
    @friends = current_user.friends << @user
    @friend_request = current_user.sent_friend_requests.last
    # add notification
    Notification.create({
      user_id: current_user.id,
      recipient_id: @user.id,
      :friendship_id => @friend_request.id,
      key_name: 'friend_request'
    })
  end

  # cancel friend request
  def cancel
    @request = Friendship.find(params[:id])
    @request.destroy
  end

  # Accept friend request
  def accept
    @user = User.find(params[:user_id])
    @friends = current_user.friends << @user
    # add notification
    Notification.create({
      user_id: current_user.id,
      recipient_id: @user.id,
      friendship_id: current_user.friendships.last.id,
      key_name: 'friend_accept'
    })
    current_user.followings.delete(@user)
    current_user.followers.delete(@user)
  end

  # Destroy friendship
  def destroy
    @user = User.find(params[:id])
    current_user.friends.destroy(@user)
    current_user.inverse_friends.destroy(@user)
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  
  protected

    def after_sign_up_path_for(resource)
      flash[:tracker] = {
        :event => 'Signup',
        :data => {'Method' => 'Email'}        
      }
      wizard_users_path(:step => 1)
    end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  prepend_before_filter :verify_user, only: [:destroy]

  private

    def verify_user
      redirect_to new_user_session_path, notice: 'You have already signed out. Please sign in again.' and return unless user_signed_in?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def social_links(profile)
    return unless profile
    links = ['angellist', 'linkedin', 'twitter', 'facebook']
    social_links = ''
    links.each do |link|
      if profile[link].present?
        link_title = profile[link]
        link_title.slice! "https://"
        link_title.slice! "http://"
        link_title.slice! "www."
        link_title = truncate(link_title, :length => 25)

        actual_like = profile[link]
        actual_like = 'http://' + actual_like
        social_link = "<div class='userProfileLeftLink'>
          <a class='#{link}' href='#{actual_like}' target='blank' style='color:rgb(130,130,130)'></a>
        </div>"
        social_links << social_link
      end
    end
    social_links.html_safe
  end
  def websites(profile)
    return unless profile
    html = '<ul class="list-unstyled">'
    profile.website.each do |link|
      link_sanitized = link
      unless link[/^https?:\/\//]
        link_sanitized = "http://#{link}"
      end
      html << "<li><a rel='nofollow' href='#{link_sanitized}' target='blank'>#{link}</a></li>"    
    end
    html << '</ul>'
    html.html_safe
  end

  def connection_numbers(profile, connection)
    number = 0
    return number unless profile
    if profile[connection].present?
      number = profile[connection]
    end
    return number
  end

end

app/views/users/wizard/step_2.html.erb
<%= content_for :title do %>
  Follow at least 3 Groups
  <%= link_to 'Skip >>', wizard_users_path(:step => params[:step].to_i + 1), :class => 'btn btn-default pull-right', :id => 'skip-step-2' %>
  <%= link_to 'Next', wizard_users_path(:step => params[:step].to_i + 1), :class => 'btn btn-success pull-right', :style => 'display:none', :id => 'continue-step-2' %>
<% end %>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="row">
      <%= render 'groups/groups', :groups => @groups %>
      <%= paginate @groups, :previous_label => 'Previous', :next_label => 'Next', :inner_window => 2, :outer_window => 0 %>
    </div>
  </div>
</div>

app/views/users/wizard/step_3.html.erb
<%= content_for :title do %>
  Additional details
  <%= link_to 'Skip >>', my_profile_path, :class => 'btn btn-default pull-right'  %>
  <p style="font-size:12px;">Please fill in as many fields as possible to use Starterpad with functionality.</p>
<% end %>
<div class="row">
  <div class="col-md-12 col-sm-8 col-xs-12">
    <%= form_for current_user, :url => user_path(current_user) do |f| %>
    <%= f.fields_for :profile do |p| %>
      <% if true %>
      <%= hidden_field_tag 'next', my_profile_path %>

      <div class="infoBlokName">
        Looking for
      </div>
      <div class="infoBlok">
        <div class="infoBlokInside">
          <div class="formRow required">
            <div class="col-md-4 col-sm-4 col-xs-12 frLeft">
              <span>Interested in markets</span>
              <br/>
              Example: 
              <span class="keyword">Social network</span><span class="keyword">Apps</span>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-12 frRight">
              <%= p.select :markets_interested_in, options_for_select(Keyword.markets.order(:title).map{ |c| [c.title, c.url, {'data-followers-count'=>c.followers_count}, {'data-startups-count' => c.startups_count}] }, selected_key = p.object.markets_interested_in),{}, {:multiple => true, :id => 'user_profile_attributes_markets_interested_in', :style => "width:100%"} %>
            </div>
            <div style="clear:both"></div>
          </div>
          <div class="formRow required">
            <div class="col-md-4 col-sm-4 col-xs-12 frLeft">
              <span>Looking for</span>
              <br/>
              Example: web developers
            </div>
            <div class="col-md-8 col-sm-8 col-xs-12 frRight">
              <%= p.text_field :looking_for %>
            </div>
            <div style="clear:both"></div>
          </div>
          <div class="formRow required">
            <div class="col-md-4 col-sm-4 col-xs-12 frLeft">
              <span>Activate "Let's talk"</span>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-12 frRight">
               
              <%= p.check_box :ask_me, :id=>'user_ask_me' %>
              <%= f.label :ask_me, '<span></span> It encourages people to ask you something and make a connection with you.'.html_safe %>
             
             
            </div>
            <div style="clear:both"></div>
          </div>
        </div>
      </div>

      <div class="infoBlokName">
        Join a new startup
      </div>
      <div class="infoBlok">
        <div class="infoBlokInside">
          <div class="formRow required">
            <div class="col-md-4 col-sm-4 col-xs-12 frLeft">
              <span>I want to join a new startup</span>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-12 frRight">
              <%= p.check_box :startup_join, style: "margin-right:7px; margin-top:3px;", id: "user_startup_join" %>
               <%= f.label :startup_join, '<span></span>'.html_safe %>
            </div>
            <div style="clear:both"></div>
          </div>
          <div class="formRow required">
            <div class="col-md-4 col-sm-4 col-xs-12 frLeft">
              <span>Conditions to join</span>
              <br/>
              Example: I can join as Co-Founder and Web Designer  
            </div>
            <div class="col-md-8 col-sm-8 col-xs-12 frRight">
              <%= p.text_field :startup_conditions %>
            </div>
            <div style="clear:both"></div>
          </div>
          <div class="formRow required">
            <div class="col-md-4 col-sm-4 col-xs-12 frLeft">
              <span>Value I can add</span>
              <br/>
              Example: I have marketing skills
            </div>
            <div class="col-md-8 col-sm-8 col-xs-12 frRight">
              <%= p.text_field :startup_add_value %>
            </div>
            <div style="clear:both"></div>
          </div>
        </div>
      </div>
    <% end %>

    <div class="infoBlokName">
      Links
    </div>
    <div class="infoBlok">
      <div class="infoBlokInside">
        <div class="formRow">
          <div class="col-md-4 col-sm-4 col-xs-12 frLeft">
            <span>Your homepage/portfolio</span>
          </div>
          <div class="col-md-8 col-sm-8 col-xs-12 frRight" id="fieldLinks">
            <%= p.select :website, current_user.profile.website ,{},{:multiple => true, :id => 'user_profile_attributes_website', :style => "width:100%"} %>
          </div>
          <div style="clear:both"></div>
        </div>
        <div class="formRow">
          <div class="col-md-4 col-sm-4 col-xs-12 frLeft">
            <span>AngelList profile link</span> 
          </div>
          <div class="col-md-8 col-sm-8 col-xs-12 frRight" id="fieldLinks">
            <%= p.text_field :angellist %>
          </div>
          <div style="clear:both"></div>
        </div>
        <div class="formRow">
          <div class="col-md-4 col-sm-4 col-xs-12 frLeft">
            <span>Twitter profile link</span> 
          </div>
          <div class="col-md-8 col-sm-8 col-xs-12 frRight" id="fieldLinks">
            <%= p.text_field :twitter %>
          </div>
          <div style="clear:both"></div>
        </div>
        <div class="formRow">
          <div class="col-md-4 col-sm-4 col-xs-12 frLeft">
            <span>Linkedin profile link</span>  
          </div>
          <div class="col-md-8 col-sm-8 col-xs-12 frRight" id="fieldLinks">
            <%= p.text_field :linkedin %>
          </div>
          <div style="clear:both"></div>
        </div>
      </div>
    </div>

      <div class="infoBlokName">
        Experience
      </div>
      <div class="infoBlok">
        <div class="infoBlokInside">
          <div class="formRow required">
            <label>Tell us some about yourself, work & startup experience</label>
            <%= p.text_area :experience, style: "width:100%; height:160px;" %>
          </div>
        </div>
      </div>

    <div class="infoBlokInside" style="padding-left:0px; padding-right:0px; padding-top:27px;">
     <%= f.submit "Update", class: "btn btn-primary", style: "width:100px; margin-right:20px; float:right" %>
     <% end %>
     <% end %>
      <div style="float:left;">
        <%= link_to "Deactivate account", '/deactivate_account', style: "margin-left:10px;" %>
      </div>
    </div>


  </div>
</div>