config/routes.rb
Starterpad::Application.routes.draw do
  
  ActiveAdmin.routes(self)
  # Devise
  devise_for :users, :controllers => { :registrations => "user/registrations", confirmations: 'user/confirmations', sessions: 'user/sessions' }

  resources :notifications
  resources :conversations, :only => [:index, :create, :show, :update] do
    member do
      get :hide
    end
  end
  resources :private_messages

  # CakePHP Redirections
  get 'group/:id', to: redirect('/groups/%{id}')
  get 'startups/index', to: redirect('/startups')
  get 'startup/:id', to: redirect('/startups/%{id}')  
  get 'startups/index/keywords:(:market_id)', to: redirect { |path_params, req| "/startups/markets/#{path_params[:market_id].to_url}" }, :constraints => { :market_id => /[^\/]+/ }
  get 'starters/skill:(:keyword_id)', to: redirect { |path_params, req| "/starters/skill/#{path_params[:keyword_id].to_url}" }, :constraints => { :keyword_id => /[^\/]+/ }
  get 'starters/role:(:role_id)', to: redirect { |path_params, req| "/starters/role/#{path_params[:role_id].to_url}" }
  get 'users/view/:id/page:page_id', to: redirect { |path_params, req| 
    path_params[:page_id][0] = '' if path_params[:page_id]
    path_params[:page_id] = 'friends' if path_params[:page_id] == 'connections'
    "/#{path_params[:id]}/#{path_params[:page_id]}" 
  }
  get 'pages/display/privacy', to: redirect('/privacy')


  resources :startups, :controller => 'startups' do
    collection do
      get :my_startups
      get :following_startups
      get 'pages/:page' => :index
      get 'markets/:market_id(/:page)' => :by_market, :as => :market
      post 'country'
      get 'country(/:title(/:page))' => "startups#country", :as => :get_by_country
      get 'country_auto_complete'
      post 'city'
      get 'city(/:name(/:page))' =>  "startups#city", :as => :get_by_city
      get 'city_auto_complete'
      get 'autocomplete'
    end
    resources :posts, only: [:create, :destroy, :index], controller: 'startup_posts'
    member do
      post :follow
      post :unfollow
    end
  end
  resources :starters, :controller => 'users', :only => [:index] do
    collection do
      get 'pages/:page' => :index
      get 'role/:role_id(/:page)' => :by_role, :as => :role
      get 'skill/:keyword_id(/:page)' => :by_keyword, :as => :skill
      post 'country'
      get 'country(/:title(/:page))' => "users#country", :as => :get_by_country
      get 'country_auto_complete'
      post 'city'
      get 'city(/:name(/:page))' => "users#city", :as => :get_by_city
      get 'city_auto_complete'
    end
  end
  resources :groups do
    member do
      post 'join/:user_id' => :join, :as => :join
      delete 'leave/:user_id' => :leave, :as => :leave
      post 'suggest_to_friend' => :suggest_to_friend, :as => :suggest_to_friend
    end
    resources :posts, only: [:create, :destroy, :index], controller: 'group_posts'
    collection do
      get 'autocomplete'
      get 'pages/:page' => :index
      get 'my_groups(/pages/:page)' => :my_groups, :as => :my
      get 'my_moderated_groups(/pages/:page)' => :my_moderated_groups, :as => :my_moderated
    end
  end
  resources :posts, :except => [:index] do
    collection do
      get 'pages/:page' => :index
    end
    resources :comments, :only => [:create, :index, :destroy]
    resources :likes, :only => [:index, :create, :destroy]
  end

  resources :users, only: [:update] do
    collection do
      get 'step/:step' => :wizard, :as => :wizard
      put :ping
    end
    resources :friends, :controller => 'user/friendships', :only => [:create, :destroy] do
      member do
        delete :cancel
        put :accept
      end
    end
    collection do
      get :friends, :to => 'user/friendships', :format => :json
    end
    member do
      match :update_settings , :to => 'users#update_settings', :via => [:patch]
    end
    resource :followerships, :controller => 'user/followerships', :only => [:create, :destroy]
  end

  resources :contact, :only => [:index, :create]
  
  authenticated :user do
    get '/', :to => "pages#pad"
  end
  
  devise_scope :user do
    get '/', :to => 'pages#home'
  end

  root :to => 'pages#home'

  # OAuth
  get 'auth/:provider/disconnect', to: 'sessions#disconnect'
  get 'auth/:provider/callback', to: 'sessions#connect'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'facebook_disconnect', to: 'user_facebooks#facebook_disconnect', as: 'facebook_disconnect'
  get 'twitter_disconnect', to: 'user_twitters#twitter_disconnect', as: 'twitter_disconnect'

  # Pages
  get '/badges' => 'pages#badges'
  get '/privacy' => 'pages#privacy'
  get '/terms' => 'pages#terms'

  # Users
  get 'profile', :to => 'users#profile', :as => 'my_profile'
  get 'profile/details',  to: 'users#profile_details', :as => 'my_profile_details'
  get 'profile/change_password',  to: 'users#change_password', :as => 'change_password'
  get 'profile/email_settings',  to: 'users#email_settings', :as => 'email_settings'
  get 'profile/social_network_settings', to: 'users#social_network_settings', as: 'social_network_settings'
  match 'profile/email_addresses', to: 'users#email_addresses', as: :user_email_addresses, via: [:get, :post]
  match 'profile/twitter_update_settings', to: 'users#twitter_update_settings', as: 'twitter_update_settings', via: [:get, :patch]

  get '/user_online_ping',  to: 'users#online_ping', :as => 'user_online_ping'
  get '/sign_action',  to: 'users#sign_action', :as => 'sign_action'
  match 'deactivate_account', to: 'users#deactivate_account', via: [:get, :post], as: 'deactivate_account'  
  match 'resend_confirmation', to: 'users#resend_confirmation', via: [:post], as: 'resend_confirmation'  
  # Conversations
  get '/inbox' => 'conversations#index'

  # Keywords
  resources :keywords, only: [:index]

  # Friends
  get '/contacts' => 'user/friendships#my_friends', :as => "my_friends"

  # Cronjobs
  get '/cronjobs/begin' => 'cronjobs#begin'
  
  # at the moment commenting out this routes, there are no sign of this usage.
  # get '/follow_startup/:id',  to: 'startup_followers#create', :as => "follow_startup"
  get '/startup_followers/:id',  to: 'followers#index', :as => "startup_followers"
   
  get ':url/friends(/page/:page)', :to => 'user/friendships#index', :as =>'friends'
  get ':url/followers(/page/:page)', :to => 'user/followerships#index', :as =>'followers'
  get ':url/followings(/page/:page)', :to => 'user/followerships#followings', :as =>'followings'

  # For Deployment
  # post 'deploy/T5ns7Pqv3G6' => 'deployments#deploy'

  # Test
  match 'test', via: :get, to: lambda {|id| 
    html = 'test'
    [200, {'Content-Type' => 'text/plain'} , [html]] 
  }

  # DISCUSS
  
  resources :items, path: 'discuss', except: [:destroy] do
    
    resources :item_comments

    collection do
      get :newest, to: 'items#newest'
    end
    member do      
      post :toggle
      post :vote, to: 'user_item_votes#create'
      delete :vote, to: 'user_item_votes#destroy'
    end
  end

  # Show User (Always the last one)
  get ':url', :to => 'users#show', :as =>'profile', constraints: ActiveUserConstraint

end

app/controllers/group_posts_controller.rb
class GroupPostsController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :destroy]
  before_action :is_active?

  def create
    #raise params.inspect
    @group = Group.where(url: params[:group_id]).first
    @group = Group.find(params[:group_id]) if @group.blank?

    if @group.members.include?(current_user) || @group.user_id == current_user.id
      @post = @group.posts.create(params[:post].merge(user: current_user))
      Notification.generate_for_group_post(@post.id, current_user.id, params[:group_id]) if @post.valid?
    else
      flash[:error] = "Only members can post in this group."
      redirect_to request.referer.present? ? :back : root_path
      return false
    end
  end

  def destroy
    @post = current_user.owned_startups.where(url: params[:startup_id]).first.posts.find(params[:id])
    if @post.destroy
      render :destroy
    else 
      render :undestroyed
    end
  end

  private

    def authenticate_user!
      super
    end

end

app/helpers/group_posts_helper.rb
module GroupPostsHelper
end

app/views/group_posts/_post.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="postTab" id="post<%= post.id %>">
      <div class="postTabPost">
        <div class="col-md-2 col-sm-2 postPhoto">
          <%= link_to profile_path(post.user) do %>
            <%= image_tag post.user._photo(:thumb), :class => "img-responsive", :onError => "this.onerror=null;this.src='images/user.png';" %>
          <% end %>
        </div>
        <div class="col-md-10 col-sm-10 postText">
          <div class="padPostTitle">
            <%= link_to post.user.title, profile_path(post.user) %>
            <div style="float:right; padding-left:15px; margin-right:1px; margin-top:0px;">
              <div style="float:right">
                <% if !defined?(group) %>
                    <% if post.comments.blank? %>
                        <a class="addCommentLink postTool" href="#" data-post-id="<%= post.id %>" data-no-turbolink>Comment</a>
                    <% end %>
                    <% my_like = post.likes.select { |l| l.user_id == current_user.id } %>
                    <% unless post.user_id == current_user.id %>
                        <a class="like postTool" id="like-post-<%= post.id %>" href="#" style="<%= my_like.blank? ? '' : 'display:none;' %>">
                          <%= image_tag 'old/gem_gray_18.png', :class => 'give-a-gem', :title => "Give a Gem" %>
                          <%= form_for [post, post.likes.build], :remote => true do |f| %>
                              <%= f.hidden_field :post_id %>
                              <%= f.hidden_field :recipient_id, :value => post.user_id %>
                          <% end %>
                        </a>
                    <% end %>
                    <%= link_to post_like_path(post, my_like), :method => :delete, :remote => true, :style => "float:left; #{my_like.blank? ? 'display:none;' : ''}", :id => "unlike-post-#{post.id}" do %>
                        <%= image_tag 'old/gem_18.png', :class => 'remove-the-gem', :title => "Remove Gem" %>
                    <% end %>
                <% elsif user_signed_in? && (group.members.include?(current_user) || group.user_id == current_user.id) %>
                    <% if post.comments.blank? %>
                        <a class="addCommentLink postTool" href="#" data-post-id="<%= post.id %>" data-no-turbolink>Comment</a>
                    <% end %>
                    <% my_like = post.likes.select { |l| l.user_id == current_user.id } %>
                    <% unless post.user_id == current_user.id %>
                      <a class="like postTool" id="like-post-<%= post.id %>" href="#" style="<%= my_like.blank? ? '' : 'display:none;' %>">
                        <%= image_tag 'old/gem_gray_18.png', :class => 'give-a-gem', :title => "Give a Gem" %>
                        <%= form_for [post, post.likes.build], :remote => true do |f| %>
                            <%= f.hidden_field :post_id %>
                            <%= f.hidden_field :recipient_id, :value => post.user_id %>
                        <% end %>
                      </a>
                      <% end %>
                    <%= link_to post_like_path(post, my_like), :method => :delete, :remote => true, :style => "float:left; #{my_like.blank? ? 'display:none;' : ''}", :id => "unlike-post-#{post.id}" do %>
                        <%= image_tag 'old/gem_18.png', :class => 'remove-the-gem', :title => "Remove Gem" %>
                    <% end %>
                <% end %>
                <div style="float:left; font-size:12px; margin-left:1px;">
                  (<a id="like-count-<%= post.id %>" href="#" style="font-weight:bolder;">
                  <%= post.likes_count && post.likes_count > 0 ? post.likes_count : "0" %>
                </a>)
                <div style="float:right;font-size:14px; font-weight:normal; margin-left:5px; ">
                  <%= link_to('Delete', post_path(post), method: :delete, remote: true, :class => "btn btn-danger btn-xs", :data => {:confirm => "Are you sure?"}) if is_admin? %>
                </div>   
                </div>
              </div>
            </div>
          </div>
          <%= auto_link(simple_format(post.text), :html => { :target => '_blank' }) %>
          <i class="fa fa-clock-o time_ago"></i>
          <%= "#{time_ago_in_words(post.created_at)} ago" %>
        </div>
      </div>
      <div class="row postTabComments">
        <% post.comments.each do |comment| %>
            <%= render 'comments/comment', comment: comment %>
        <% end %>
        <% if user_signed_in? %>
        <div class="col-md-12 col-sm-12 addComment comment-on-<%= post.id %>" id="addComment_post<%= post.id %>">
          <%= form_for post.comments.build, url: post_comments_path(post), remote: true do |f| %>
              <div class="col-md-12 col-sm-12">
                <%= f.text_area :text, class: 'postCommentTextarea pull-left', placeholder: "Write a comment...", cols: "30", rows: "6" %>
                <div class="submit">
                  <%= button_tag "Post", class: "commentPostBtn", style: "height: 35px; float:left; margin: 0;", 'data-disable-with' => "<i class='fa fa-spinner fa-spin'></i>".html_safe %>

                </div>
              </div>
              <!-- <div class="submit"><input type="submit" value="Post" class="commentPostBtn"></div> -->
              <div class="clearfix"></div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/group_posts/create.js.erb
<% if @post.errors.present? %>
  <% 
    errors = []
    @post.errors.messages.values.each do |message|
      errors += message
    end
  %>
  $('.pageContent').prepend("<%= j render(partial: '/shared/js_error_messages', collection: errors, as: :error) %>");
<% else %>
  $('#postsList').prepend('<%= j(render("post", post: @post)) %>');
  $("#addPostArea textarea").val('');
<% end %>