config/routes.rb
Starterpad::Application.routes.draw do
  
  ActiveAdmin.routes(self)
  # Devise
  devise_for :users, :controllers => { :registrations => "user/registrations", confirmations: 'user/confirmations', sessions: 'user/sessions' }

  resources :notifications
  resources :conversations, :only => [:index, :create, :show, :update] do
    member do
      get :hide
    end
  end
  resources :private_messages

  # CakePHP Redirections
  get 'group/:id', to: redirect('/groups/%{id}')
  get 'startups/index', to: redirect('/startups')
  get 'startup/:id', to: redirect('/startups/%{id}')  
  get 'startups/index/keywords:(:market_id)', to: redirect { |path_params, req| "/startups/markets/#{path_params[:market_id].to_url}" }, :constraints => { :market_id => /[^\/]+/ }
  get 'starters/skill:(:keyword_id)', to: redirect { |path_params, req| "/starters/skill/#{path_params[:keyword_id].to_url}" }, :constraints => { :keyword_id => /[^\/]+/ }
  get 'starters/role:(:role_id)', to: redirect { |path_params, req| "/starters/role/#{path_params[:role_id].to_url}" }
  get 'users/view/:id/page:page_id', to: redirect { |path_params, req| 
    path_params[:page_id][0] = '' if path_params[:page_id]
    path_params[:page_id] = 'friends' if path_params[:page_id] == 'connections'
    "/#{path_params[:id]}/#{path_params[:page_id]}" 
  }
  get 'pages/display/privacy', to: redirect('/privacy')


  resources :startups, :controller => 'startups' do
    collection do
      get :my_startups
      get :following_startups
      get 'pages/:page' => :index
      get 'markets/:market_id(/:page)' => :by_market, :as => :market
      post 'country'
      get 'country(/:title(/:page))' => "startups#country", :as => :get_by_country
      get 'country_auto_complete'
      post 'city'
      get 'city(/:name(/:page))' =>  "startups#city", :as => :get_by_city
      get 'city_auto_complete'
      get 'autocomplete'
    end
    resources :posts, only: [:create, :destroy, :index], controller: 'startup_posts'
    member do
      post :follow
      post :unfollow
    end
  end
  resources :starters, :controller => 'users', :only => [:index] do
    collection do
      get 'pages/:page' => :index
      get 'role/:role_id(/:page)' => :by_role, :as => :role
      get 'skill/:keyword_id(/:page)' => :by_keyword, :as => :skill
      post 'country'
      get 'country(/:title(/:page))' => "users#country", :as => :get_by_country
      get 'country_auto_complete'
      post 'city'
      get 'city(/:name(/:page))' => "users#city", :as => :get_by_city
      get 'city_auto_complete'
    end
  end
  resources :groups do
    member do
      post 'join/:user_id' => :join, :as => :join
      delete 'leave/:user_id' => :leave, :as => :leave
      post 'suggest_to_friend' => :suggest_to_friend, :as => :suggest_to_friend
    end
    resources :posts, only: [:create, :destroy, :index], controller: 'group_posts'
    collection do
      get 'autocomplete'
      get 'pages/:page' => :index
      get 'my_groups(/pages/:page)' => :my_groups, :as => :my
      get 'my_moderated_groups(/pages/:page)' => :my_moderated_groups, :as => :my_moderated
    end
  end
  resources :posts, :except => [:index] do
    collection do
      get 'pages/:page' => :index
    end
    resources :comments, :only => [:create, :index, :destroy]
    resources :likes, :only => [:index, :create, :destroy]
  end

  resources :users, only: [:update] do
    collection do
      get 'step/:step' => :wizard, :as => :wizard
      put :ping
    end
    resources :friends, :controller => 'user/friendships', :only => [:create, :destroy] do
      member do
        delete :cancel
        put :accept
      end
    end
    collection do
      get :friends, :to => 'user/friendships', :format => :json
    end
    member do
      match :update_settings , :to => 'users#update_settings', :via => [:patch]
    end
    resource :followerships, :controller => 'user/followerships', :only => [:create, :destroy]
  end

  resources :contact, :only => [:index, :create]
  
  authenticated :user do
    get '/', :to => "pages#pad"
  end
  
  devise_scope :user do
    get '/', :to => 'pages#home'
  end

  root :to => 'pages#home'

  # OAuth
  get 'auth/:provider/disconnect', to: 'sessions#disconnect'
  get 'auth/:provider/callback', to: 'sessions#connect'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'facebook_disconnect', to: 'user_facebooks#facebook_disconnect', as: 'facebook_disconnect'
  get 'twitter_disconnect', to: 'user_twitters#twitter_disconnect', as: 'twitter_disconnect'

  # Pages
  get '/badges' => 'pages#badges'
  get '/privacy' => 'pages#privacy'
  get '/terms' => 'pages#terms'

  # Users
  get 'profile', :to => 'users#profile', :as => 'my_profile'
  get 'profile/details',  to: 'users#profile_details', :as => 'my_profile_details'
  get 'profile/change_password',  to: 'users#change_password', :as => 'change_password'
  get 'profile/email_settings',  to: 'users#email_settings', :as => 'email_settings'
  get 'profile/social_network_settings', to: 'users#social_network_settings', as: 'social_network_settings'
  match 'profile/email_addresses', to: 'users#email_addresses', as: :user_email_addresses, via: [:get, :post]
  match 'profile/twitter_update_settings', to: 'users#twitter_update_settings', as: 'twitter_update_settings', via: [:get, :patch]

  get '/user_online_ping',  to: 'users#online_ping', :as => 'user_online_ping'
  get '/sign_action',  to: 'users#sign_action', :as => 'sign_action'
  match 'deactivate_account', to: 'users#deactivate_account', via: [:get, :post], as: 'deactivate_account'  
  match 'resend_confirmation', to: 'users#resend_confirmation', via: [:post], as: 'resend_confirmation'  
  # Conversations
  get '/inbox' => 'conversations#index'

  # Keywords
  resources :keywords, only: [:index]

  # Friends
  get '/contacts' => 'user/friendships#my_friends', :as => "my_friends"

  # Cronjobs
  get '/cronjobs/begin' => 'cronjobs#begin'
  
  # at the moment commenting out this routes, there are no sign of this usage.
  # get '/follow_startup/:id',  to: 'startup_followers#create', :as => "follow_startup"
  get '/startup_followers/:id',  to: 'followers#index', :as => "startup_followers"
   
  get ':url/friends(/page/:page)', :to => 'user/friendships#index', :as =>'friends'
  get ':url/followers(/page/:page)', :to => 'user/followerships#index', :as =>'followers'
  get ':url/followings(/page/:page)', :to => 'user/followerships#followings', :as =>'followings'

  # For Deployment
  # post 'deploy/T5ns7Pqv3G6' => 'deployments#deploy'

  # Test
  match 'test', via: :get, to: lambda {|id| 
    html = 'test'
    [200, {'Content-Type' => 'text/plain'} , [html]] 
  }

  # DISCUSS
  
  resources :items, path: 'discuss', except: [:destroy] do
    
    resources :item_comments

    collection do
      get :newest, to: 'items#newest'
    end
    member do      
      post :toggle
      post :vote, to: 'user_item_votes#create'
      delete :vote, to: 'user_item_votes#destroy'
    end
  end

  # Show User (Always the last one)
  get ':url', :to => 'users#show', :as =>'profile', constraints: ActiveUserConstraint

end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id                 :integer          not null, primary key
#  user_id            :integer
#  recipient_id       :integer
#  last_action_at     :datetime
#  new                :boolean
#  private_message_id :integer
#  user_hide          :boolean
#  recipient_hide     :boolean
#  created_at         :datetime
#  updated_at         :datetime
#

class Conversation < ActiveRecord::Base

  attr_accessible :hidden, :last_action, :private_message_id, :new, :last_action_at,
    :recipient_id, :user_id, :recipient_hide, :user_hide, :messages_attributes

  has_many :messages, :dependent => :destroy
  belongs_to :sender, :class_name => 'User', :foreign_key => 'user_id'
  belongs_to :receiver, :class_name => 'User', :foreign_key => 'recipient_id'
  # TODO: has_one instead of belongs_to
  has_one :last_message, -> { order('created_at DESC')}, :class_name => 'Message'

  validates_uniqueness_of :user_id, :scope => [:recipient_id]

  accepts_nested_attributes_for :messages, reject_if: proc { |attributes| attributes['text'].blank? }

  class << self
    def with(user, other_user, opt={})
      # If ids are passed instead of user objects..
      if opt[:ids]
        conditions = {:this_user => user, :other_user => other_user}
      else
        conditions = {:this_user => user.id, :other_user => other_user.id}
      end
      where(
        '(user_id = :this_user and recipient_id = :other_user) OR (recipient_id = :this_user and user_id = :other_user)',
        conditions
      ).first
    end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  
  before_filter :authenticate_user!
  before_action :is_active?, :except => [:index]

  # All conversations
  def index
    @conversations = Conversation.includes(:last_message, :sender, :receiver).where(
      "(user_id = ? AND user_hide IS NOT TRUE) OR (recipient_id = ? AND recipient_hide IS NOT TRUE)",
    current_user.id, current_user.id).order('updated_at DESC').page(params[:page]).per(10)
  end

  def create    
    @conversation = Conversation.new(params[:conversation])
    if @conversation.save
      flash[:success] = 'Your Message has been sent successfully'
      send_conversation_email(@conversation)
      redirect_to conversation_path(@conversation.recipient_id)
    else
      flash[:danger] = 'There was an error, Please try again!'
      redirect_to conversation_path(@conversation.recipient_id)
    end
  end

  def update
    @conversation = Conversation.find(params[:id])
    if @conversation.recipient_id === current_user.id 
      recipient = @conversation.user_id
    else
      recipient =  @conversation.recipient_id
    end

    data = {
      "messages_attributes" => {
        "0" => {
          "text" => params[:conversation][:messages_attributes]["0"][:text],
          "user_id" => current_user.id,
          "recipient_id" => recipient
        }
      }
    }
    if @conversation.update_attributes(data)
      flash[:success] = 'Your Message has been sent successfully'
      send_conversation_email(@conversation)
      redirect_to conversation_path(recipient)
    else
      flash[:danger] = 'There was an error, Please try again!'
      redirect_to conversation_path(recipient)
    end
  end

  # Hide
  def hide
    conversation = Conversation.find(params[:id])

    conversation.user_id == current_user.id ? conversation.user_hide = true : conversation.recipient_hide = true
    conversation.messages.update_all(:new => false) if conversation.save

    flash[:success] = "Done!"
    redirect_to conversations_url
  end

  def show
    @user = User.find(params[:id])
    if @user == current_user      
      redirect_to '/conversations'
      return
    end

    @conversation = Conversation.with(current_user, @user)
    if @conversation.blank?
      @conversation = Conversation.new(:recipient_id => @user.id, :user_id => current_user.id)
      @messages = []
    else
      @messages = @conversation.messages.sort_by &:created_at
      Message.where("recipient_id = ? and user_id = ? and new = true ", current_user.id, @user.id).update_all(:new => false)
    end

    @message = Message.new(:recipient_id => @user.id, :user_id => current_user.id)
  end

  protected

  def send_conversation_email(conversation)
    @receiver = conversation.last_message.receiver
    if !@receiver.online? &&  @receiver.setting.private_messages
      UserMailer.new_message(conversation.last_message).deliver
    end
  end

end

app/views/conversations/index.html.erb
<%
meta :title => "Private Messages",
     :description => "The history of all messages you've sent to other StarterPad members.",
     :keywords => "messages, starterpad"
%>
<% content_for :title do %>
	Private Messages
<% end %>
<div class="row">
	<div class="col-md-8 col-sm-8 col-xs-12">
		<ul class="privateMessagesUl">
			<% @conversations.each do |c|
				opponent = c.user_id == current_user.id ? c.receiver : c.sender
			%>

				<% if defined? opponent.title %>
					<li class="<%= 'new' if c.last_message && c.last_message.receiver == current_user && c.last_message.new %>">
						<%= link_to conversation_path(opponent.id) do %>
							<div class="pmPhoto col-md-2 col-sm-3 col-xs-4">
								<%= image_tag opponent._photo(:thumb), :class => "img-responsive img-thumbnail" %>
							</div>
							<div class="pmText col-md-9 col-sm-7 col-xs-7">
									<%= opponent.title %>
									<br/>
									<% if !c.last_message.nil? %>
									<span class="pull-left text-muted"><small><%= c.last_message.created_at.strftime("%b %d, %Y")%></small></span>
									<br/>
									<% end %>
								<span class="" style="color:#000000; line-height:120%;">
									<% if !c.last_message.nil? %>
										<%= truncate(c.last_message.text.tr("'",'"').tr("\n", " ").tr("\r", " "), :length =>150) %>
									<% end %>
								</span>	
							</div>
						<% end %>
						<div class="col-md-1 col-sm-2 col-xs-1"> 
							<%= link_to 'hide', hide_conversation_path(c), data: { confirm: "Are you sure want to hide this conversation?" }, style: "font-size:13px; ", class: "hide_link" 
							%>
						</div>
						<div style="clear:both;"></div>
					</li>
				
				<% end %>

			<% end %>
		</ul>
		<% if @conversations.blank? %>
			<span>You don't have any messages</span>
		<% end %>
		<div style="margin-right:25px; margin-top:10px;">
			<%= paginate @conversations, :previous_label => 'Previous', :next_label => 'Next', :inner_window => 2, :outer_window => 0 %>
		</div>
	</div>

	<div class="col-md-4 col-sm-4 col-xs-12 ">
	    <%= render 'users/partials/menu' %>
	</div>
</div>

app/views/conversations/show.html.erb
<% content_for :title do %>
<%= (params[:ask].present?) ?
	('Ask something and make a connection with ' + link_to(@user[:title], profile_path(@user))).html_safe : 
	('Conversation with ' + link_to(@user[:title], profile_path(@user))).html_safe %>
<% end %>
<div class="row">
	<div class="col-md-8 col-sm-8 col-xs-12">
		<ul class="conversationUl">
		<% @messages.each do |m| %>
			<li>
				<div class="photo">		
					<%= image_tag m.sender.photo.url(:small) %>
				</div>
				<div class="text">
					<span><%= link_to m.sender.title, profile_path(m.sender.url), :class => "#{'text-warning' if m.sender != current_user}" %></span>
					<span class="pull-right text-muted"><small><%= m.created_at.strftime("%b %d, %Y")%></small></span>
					<br/>
					<%=raw auto_link(simple_format(sanitize(m.text)), :html => { :target => '_blank' }) %>
				</div>	
			</li>
		<% end %>
		</ul>
		<div class="conversationReply">
			<%= form_for @conversation do |f| %>
				<%= f.hidden_field :recipient_id %>
				<%= f.hidden_field :user_id %>
				<%= f.fields_for :messages, @message do |p| %>
					<%= p.text_area :text, :class => 'form-control', placeholder: "Write a message..." %>
					<%= p.hidden_field :recipient_id %>
					<%= p.hidden_field :user_id %>
					<%= p.hidden_field :new %>
					<%= p.submit "Send »", class: "btn btn-primary" %>
				<% end %>
			<% end %>
		</div>
	</div>
	<div class="col-md-4 col-sm-4 col-xs-12">
	    <%= render 'users/partials/menu' %>
	</div>
</div>