config/routes.rb
Starterpad::Application.routes.draw do
  
  ActiveAdmin.routes(self)
  # Devise
  devise_for :users, :controllers => { :registrations => "user/registrations", confirmations: 'user/confirmations', sessions: 'user/sessions' }

  resources :notifications
  resources :conversations, :only => [:index, :create, :show, :update] do
    member do
      get :hide
    end
  end
  resources :private_messages

  # CakePHP Redirections
  get 'group/:id', to: redirect('/groups/%{id}')
  get 'startups/index', to: redirect('/startups')
  get 'startup/:id', to: redirect('/startups/%{id}')  
  get 'startups/index/keywords:(:market_id)', to: redirect { |path_params, req| "/startups/markets/#{path_params[:market_id].to_url}" }, :constraints => { :market_id => /[^\/]+/ }
  get 'starters/skill:(:keyword_id)', to: redirect { |path_params, req| "/starters/skill/#{path_params[:keyword_id].to_url}" }, :constraints => { :keyword_id => /[^\/]+/ }
  get 'starters/role:(:role_id)', to: redirect { |path_params, req| "/starters/role/#{path_params[:role_id].to_url}" }
  get 'users/view/:id/page:page_id', to: redirect { |path_params, req| 
    path_params[:page_id][0] = '' if path_params[:page_id]
    path_params[:page_id] = 'friends' if path_params[:page_id] == 'connections'
    "/#{path_params[:id]}/#{path_params[:page_id]}" 
  }
  get 'pages/display/privacy', to: redirect('/privacy')


  resources :startups, :controller => 'startups' do
    collection do
      get :my_startups
      get :following_startups
      get 'pages/:page' => :index
      get 'markets/:market_id(/:page)' => :by_market, :as => :market
      post 'country'
      get 'country(/:title(/:page))' => "startups#country", :as => :get_by_country
      get 'country_auto_complete'
      post 'city'
      get 'city(/:name(/:page))' =>  "startups#city", :as => :get_by_city
      get 'city_auto_complete'
      get 'autocomplete'
    end
    resources :posts, only: [:create, :destroy, :index], controller: 'startup_posts'
    member do
      post :follow
      post :unfollow
    end
  end
  resources :starters, :controller => 'users', :only => [:index] do
    collection do
      get 'pages/:page' => :index
      get 'role/:role_id(/:page)' => :by_role, :as => :role
      get 'skill/:keyword_id(/:page)' => :by_keyword, :as => :skill
      post 'country'
      get 'country(/:title(/:page))' => "users#country", :as => :get_by_country
      get 'country_auto_complete'
      post 'city'
      get 'city(/:name(/:page))' => "users#city", :as => :get_by_city
      get 'city_auto_complete'
    end
  end
  resources :groups do
    member do
      post 'join/:user_id' => :join, :as => :join
      delete 'leave/:user_id' => :leave, :as => :leave
      post 'suggest_to_friend' => :suggest_to_friend, :as => :suggest_to_friend
    end
    resources :posts, only: [:create, :destroy, :index], controller: 'group_posts'
    collection do
      get 'autocomplete'
      get 'pages/:page' => :index
      get 'my_groups(/pages/:page)' => :my_groups, :as => :my
      get 'my_moderated_groups(/pages/:page)' => :my_moderated_groups, :as => :my_moderated
    end
  end
  resources :posts, :except => [:index] do
    collection do
      get 'pages/:page' => :index
    end
    resources :comments, :only => [:create, :index, :destroy]
    resources :likes, :only => [:index, :create, :destroy]
  end

  resources :users, only: [:update] do
    collection do
      get 'step/:step' => :wizard, :as => :wizard
      put :ping
    end
    resources :friends, :controller => 'user/friendships', :only => [:create, :destroy] do
      member do
        delete :cancel
        put :accept
      end
    end
    collection do
      get :friends, :to => 'user/friendships', :format => :json
    end
    member do
      match :update_settings , :to => 'users#update_settings', :via => [:patch]
    end
    resource :followerships, :controller => 'user/followerships', :only => [:create, :destroy]
  end

  resources :contact, :only => [:index, :create]
  
  authenticated :user do
    get '/', :to => "pages#pad"
  end
  
  devise_scope :user do
    get '/', :to => 'pages#home'
  end

  root :to => 'pages#home'

  # OAuth
  get 'auth/:provider/disconnect', to: 'sessions#disconnect'
  get 'auth/:provider/callback', to: 'sessions#connect'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'facebook_disconnect', to: 'user_facebooks#facebook_disconnect', as: 'facebook_disconnect'
  get 'twitter_disconnect', to: 'user_twitters#twitter_disconnect', as: 'twitter_disconnect'

  # Pages
  get '/badges' => 'pages#badges'
  get '/privacy' => 'pages#privacy'
  get '/terms' => 'pages#terms'

  # Users
  get 'profile', :to => 'users#profile', :as => 'my_profile'
  get 'profile/details',  to: 'users#profile_details', :as => 'my_profile_details'
  get 'profile/change_password',  to: 'users#change_password', :as => 'change_password'
  get 'profile/email_settings',  to: 'users#email_settings', :as => 'email_settings'
  get 'profile/social_network_settings', to: 'users#social_network_settings', as: 'social_network_settings'
  match 'profile/email_addresses', to: 'users#email_addresses', as: :user_email_addresses, via: [:get, :post]
  match 'profile/twitter_update_settings', to: 'users#twitter_update_settings', as: 'twitter_update_settings', via: [:get, :patch]

  get '/user_online_ping',  to: 'users#online_ping', :as => 'user_online_ping'
  get '/sign_action',  to: 'users#sign_action', :as => 'sign_action'
  match 'deactivate_account', to: 'users#deactivate_account', via: [:get, :post], as: 'deactivate_account'  
  match 'resend_confirmation', to: 'users#resend_confirmation', via: [:post], as: 'resend_confirmation'  
  # Conversations
  get '/inbox' => 'conversations#index'

  # Keywords
  resources :keywords, only: [:index]

  # Friends
  get '/contacts' => 'user/friendships#my_friends', :as => "my_friends"

  # Cronjobs
  get '/cronjobs/begin' => 'cronjobs#begin'
  
  # at the moment commenting out this routes, there are no sign of this usage.
  # get '/follow_startup/:id',  to: 'startup_followers#create', :as => "follow_startup"
  get '/startup_followers/:id',  to: 'followers#index', :as => "startup_followers"
   
  get ':url/friends(/page/:page)', :to => 'user/friendships#index', :as =>'friends'
  get ':url/followers(/page/:page)', :to => 'user/followerships#index', :as =>'followers'
  get ':url/followings(/page/:page)', :to => 'user/followerships#followings', :as =>'followings'

  # For Deployment
  # post 'deploy/T5ns7Pqv3G6' => 'deployments#deploy'

  # Test
  match 'test', via: :get, to: lambda {|id| 
    html = 'test'
    [200, {'Content-Type' => 'text/plain'} , [html]] 
  }

  # DISCUSS
  
  resources :items, path: 'discuss', except: [:destroy] do
    
    resources :item_comments

    collection do
      get :newest, to: 'items#newest'
    end
    member do      
      post :toggle
      post :vote, to: 'user_item_votes#create'
      delete :vote, to: 'user_item_votes#destroy'
    end
  end

  # Show User (Always the last one)
  get ':url', :to => 'users#show', :as =>'profile', constraints: ActiveUserConstraint

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id           :integer          not null, primary key
#  title        :string(60)       not null
#  slug         :string(500)
#  about        :string(510)      not null
#  long_about   :text
#  user_id      :integer          not null
#  privacy      :integer          not null
#  member_count :integer          default(1), not null
#  status       :integer          default(1)
#  homepage     :integer
#  trending     :integer
#  created      :datetime         not null
#  last_action  :datetime
#  filename     :string(510)
#

class Group < ActiveRecord::Base
  include Photoable
  include PgSearch

  # NOTE: Use this while importing form lagacy DB
  # attr_accessible :id, :title, :url, :about, :long_about, :user_id, :privacy, :members_count,
  #   :status, :homepage, :trending, :created_at, :last_action_at, :lagacy_photo
  attr_accessible :title, :about, :long_about, :photo

  # NOTE: Coment this line when importing lagacy DB
  acts_as_url :title, :limit => 50, :sync_url => true

  belongs_to :owner, :class_name => 'User', :foreign_key => 'user_id'
  validates :owner, presence: true
  validate :status_of_user_must_active

  has_many :posts, :dependent => :destroy

  has_many :memberships, -> { where :status => true }, :dependent => :destroy
  has_many :members, :through => :memberships, :source => :user

  has_attached_file :photo, 
    :path => ':rails_root/public/uploads/:class/:attachment/:id/:style/:filename',
    :url => '/uploads/:class/:attachment/:id/:style/:filename',
    :styles => { 
      :small => {
        :geometry => "40x40#",
        :quality => "93"
      }, 
      :thumb => {
        :geometry => "120x120#",
        :quality => "93"
      }, 
      :middle => {
        :geometry => "300x300>",
        :quality => "93"
      }, 
      :big => {
        :geometry => "500x500>",
        :quality => "93"
      }, 
      :large => {
        :geometry => "800x800>",
        :quality => "93"
      } 
    },
    :default_url => '/group.png'

  validates :title, :about, :long_about, :presence => true
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/, :message => 'file type is not allowed (only jpeg/png/gif images)'

  scope :active, -> { where(status: true) }

  #search scopes
  pg_search_scope :search_by_title_about, :against => [:title, :about, :long_about]


  before_create :default_values
  after_create :create_memberhip_of_owner

  def to_param
    url
  end

  private

    def default_values
      self.privacy = 0
      self.last_action_at = Time.now
      self.members_count = 0
    end

    def create_memberhip_of_owner
      self.members << owner
    end

    def status_of_user_must_active
    errors.add(:owner, I18n.t('.errors.messages.user_is_not_active')) if owner && !owner.status?

    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include InactiveUserLimits

  before_filter :authenticate_user!, :except => [:index, :show, :autocomplete]
  before_action :is_active?, :except => [:index, :show, :my_groups, :my_moderated_groups, :join, :leave]

  respond_to :js, :only => [:index, :join, :leave]

  def index
    if params[:qs]
      @query = params[:qs]
      @search = Group.active.search_by_title_about(params[:qs]).includes(:members).search(search_params)    
    else
      @search = Group.active.includes(:members).search(search_params)
    end

    # make name the default sort column
    @search.sorts = 'name' if @search.sorts.empty?
    @groups = @search.result().page(params[:page]).per(12)
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.owned_groups.build(params[:group])
    if @group.save
      flash[:success] = 'Group created successfully'
      redirect_to group_path(@group)
    else
      flash[:danger] = @group.errors.full_messages.first
      render :new
    end
  end

  def show
    @group = Group.includes(:members).find_by_url(params[:id])
    @group = Group.includes(:members).find(params[:id]) if @group.blank?
    @post = current_user.posts.build(:group_id => @group.id) if current_user
    @posts = @group.posts.includes(:user, :likes, :comments => [:user]).order('created_at desc')
    @groups = current_user.my_suggested_groups.order('id DESC') if current_user
    @group_members = @group.members.pluck(:id)
    @already_members = current_user.friends.where.not(id: @group_members).order(:title) if current_user
  end

  def autocomplete
    @groups = Group.order("title ilike '%#{params[:qs]}%'").where('title ilike ?', "%#{params[:qs]}%").limit(5)
    output = []
    @groups.each{ |g|
      output.push({
        'title' => g.title,
        'url' => g.url,
        'photo' => g._photo(:thumb)
        })
    }
    render json: output
  end

  def edit
    @group = current_user.owned_groups.find_by_url(params[:id])

  end

  def update
    @group = current_user.owned_groups.find_by_url(params[:id])
    if @group.update_attributes(params[:group])
      flash[:success] = 'Group successfully updated'
      redirect_to group_path(@group) unless remotipart_submitted?
    else
      flash[:danger] = @group.errors.full_messages.first
      render :edit
    end
  end

  def suggest_to_friend
    @group = Group.find_by_url(params[:id])
    params["user_ids"].each do |target_id|
      Notification.generate_for_group_suggest(current_user.id, target_id, @group.id)
    end
    flash[:success] = 'Group successfully suggested'
    redirect_to group_path(@group)
  end

  def my_groups
    #@groups = current_user.groups.includes(:members).page(params[:page]).per(8).order('last_action_at desc')
    @search = current_user.groups.includes(:members).search(search_params)
    # make name the default sort column
    @search.sorts = 'name' if @search.sorts.empty?
    @groups = @search.result().page(params[:page]).per(12)
  end

  def my_moderated_groups
    @groups = current_user.owned_groups.includes(:members).page(params[:page]).per(8).order('last_action_at desc')
  end

  def join
    @group = Group.find_by_url(params[:id])
    @user = User.find(params[:user_id])
    membership = @group.memberships.build(user: @user)
    Notification.generate_for_group_join(current_user.id, @group.id)
    unless membership.save
      @errors = membership.errors.messages.map{|k,v| v.join('<br />')}
      render 'shared/add_error'
    end
  end

  def leave
    @group = Group.find_by_url(params[:id])
    @user = User.find(params[:user_id])
    @group.members.delete(@user)
  end

  def destroy
    @group = current_user.owned_groups.find_by_url(params[:id])
    if @group.destroy
      flash[:success] = 'Your Group has been deleted successfully'
      redirect_to my_moderated_groups_path
    else
      flash[:danger] = @group.errors.full_messages.first
      render :edit
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_groups.html.erb
<div class="groupstartupsList">
  <div class="col-md-12">
    <%= sort_link @search, :title, "Sort by Name" %>
  </div>
<% groups.each do |group| %>
  <div class="col-md-3 col-sm-4 col-xs-6">
    <div class="panel panel-info">
      <div class="panel-heading">
        <strong class="panel-title">
          <div class="panel-title-1">
            <% if group.title? %>
              <%= link_to truncate(group.title, :length => 100), group_path(group.url), :title => group.title %>
            <% end %>
          </div>
          <% if group.about.present? %>
            <div class="panel-title-2" title="<%= group.about %>"><%= truncate(group.about, :length => 100) if group.about? %></div>
          <% else %>
            &nbsp;
          <% end %> 
        </strong>
      </div>
      <div class="panel-body">
        <%= link_to group_path(group.url) do %>
          <%= image_tag group._photo(:thumb), :size => '122', :class => "img-responsive", :onError => "this.onerror=null;this.src='/group.png';" %>
        <% end %>
        <% if user_signed_in? %>
          <% if group.user_id == current_user.id %>
            <div class="follow_btn_area">
              <a class="userListFollowing btn btn-warning">Moderating</a>
            </div>
          <% else %>
            <div class="follow_btn_area">                             
              <%= link_to 'Join', join_group_path(group, current_user.id), :method => :post, :remote => true, :class => 'userListFollow btn btn-primary', :id => "join-link-#{group.id}", 
                :style => group.members.map(&:id).include?(current_user.id) ? 'display:none' : ''
              %>

              <%= link_to 'Joined', leave_group_path(group, current_user.id), :method => :delete, :remote => :true, :id => "joined-link-#{group.id}", :class => "userListFollow btn btn-success",  
                :style => group.members.map(&:id).include?(current_user.id) ? '' : 'display:none'%>                             
            </div>
          <% end %>
        <% end %>
        <div style="clear:both"></div>
      </div>
      <div style="clear:both"></div>  
    </div>
  </div>
<% end %>
</div>
<div style="clear:both"></div>

app/views/groups/_index_right.html.erb
<% if current_user.present? %>
	<% if current_user.status? %>
		<div class="row">
			<div class="col-md-12">
        <%= link_to new_group_path do %>
  			<i class="fa fa-plus-square fa-2x" style="color:#3cb521; vertical-align:middle;"></i>
		<% end %>
		&nbsp;&nbsp;
		<%= link_to new_group_path do %>
          Create a Group
		<% end %>
			<br><br>        
			</div>
		</div>
	<% end %>
<% end %>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Show</h3>
  </div>
  <div class="panel-body">
  	<ul>
			<li class="col-md-12 <%= params[:action] == 'index' ? 'active' : '' %>">
				<%= link_to 'All Groups', groups_path %>
			</li>
			<% if current_user.present? %>
				<li class="col-md-12 <%= params[:action] == 'my_groups' ? 'active' : '' %>">
					<%= link_to 'My Groups', my_groups_path %>
				</li>			
				<li class="col-md-12 <%= params[:action] == 'my_moderated_groups' ? 'active' : '' %>">
					<%= link_to 'Moderator Rights', my_moderated_groups_path %>
				</li>
			<% end %>      
			<% if params[:action] == 'edit' %>
				<li class="col-md-12">
					<%= link_to "Delete '#{@group.title}'", group_path(@group), :class => "btnMiddle btn btn-danger", :method => :delete, :remote => true, :confirm => "Are you sure?" %>
				</li>
			<% end %>
			<div style="clear:both"></div>
		</ul>
		<div style="clear:both"></div>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Search Groups</h3>
  </div>
  <div class="panel-body">
  	<ul>
	    <li class="col-md-12">
				<div id="keyword_field">
					<form method="get" action="">
		    			<input id="group_search_autocomplete", value="<%= params[:query] %>" name="query", style="width:100%;">
		    		</form>
			    <div style="clear:both"></div>
				</div>
			</li>
			<div style="clear:both"></div>
		</ul>
		<div style="clear:both"></div>
  </div>
</div>

app/views/groups/_medium_tab.html.erb
<div class="col-md-6 col-sm-6 col-xs-12 ">
  <div class="userTwoInLineTab">
  	<div class="photo">
  		<%= link_to group_path(group) do %>
  			<%= image_tag group._photo(:thumb) %>
  		<% end %>
  	</div>
    <div class="text">
    	<% if group.title? %>
    		<%= link_to group_path(group) do %>
    			<%= group.title %>
    		<% end %>
    	<% end %>
    	<div class="summary">
      	<% if group.about? %>
  	    	<span>
  	    		<%= truncate(group.about, :lenght => 29) %>
  	    	</span>
      	<% end %>
   		</div>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<%= content_for :title do %>
  <%= 'Edit ' + "'#{@group.title}'" %>
<% end %>
<div class="row">
  <div class="col-md-8 col-sm-8 col-xs-12">
    <div class="infoBlok">
      <div style="padding-left:20px; padding-top:20px; padding-bottom:20px;">
        <%= render 'groups/form', :group => @group %>
      </div>
    </div>
  </div>
  <div class="col-md-4 col-sm-4 col-xs-12">
    <%= render 'groups/index_right' %>
  </div>
</div>

app/views/groups/show.html.erb
<% if @group.title.present? %>
	<% keyword_full = @group.title %>
	<% keyword = keyword_full.gsub(/[^A-Z0-9a-z ]/i, '') %>
	<% keywords = keyword.split().join(",") %>
<% else %>
	<% keywords = "2014" %>
<% end %>

<%
meta :title => "#{@group.title}",
     :description => "#{@group.title} - #{@group.about} (a StarterPad group, for startup entrepreneurs to share ideas and help one another)",
     :keywords => "#{keywords},starterpad,startups,entrepreneurs,group"
%>
<% content_for :title do %>
	<div style="float:left;">
		<%= @group.title %>
	</div>
	<% if user_signed_in? %>
		<% if @group.user_id == current_user.id %>
			<div style="margin: 0 0 0 10px; float:left;">
				<%= link_to 'Edit', edit_group_path(@group), :class => "btn btn-warning btn-xs" %>
			</div>
		<% elsif @group.members.map(&:id).include?(current_user.id) %>
			<div style="margin: 0 0 0 10px; float:left;">
				<%= link_to 'Joined', leave_group_path(@group, current_user.id), :method => :delete, :remote => :true, :id => "joined-link-#{@group.id}", :class => "btn btn-success btn-xs" %>
				<%= link_to 'Join', join_group_path(@group, current_user.id, :show => true), :method => :post, :remote => true, :id => "join-link-#{@group.id}", :style => 'display:none;', :class => "btn btn-primary btn-xs" %>
			</div>
		<% else %>
		  <div style="margin: 0 0 0 10px; float:left;">
				<%= link_to 'Join', join_group_path(@group, current_user.id, :show => true), :method => :post, :remote => true, :id => "join-link-#{@group.id}", :class => "btn btn-primary btn-xs" %>
				<%= link_to 'Joined', leave_group_path(@group, current_user.id), :method => :delete, :remote => :true, :id => "joined-link-#{@group.id}", :style => 'display:none;', :class => "btn btn-success btn-xs" %>
			</div>
  	<% end %>
	<% end %>
<% end %>
<div class="row">
	<div class="col-md-8 col-sm-8 col-xs-12">
	  <div id="group" class="padPosts">
	  	<div class="row">
		  	<div class="col-md-12 col-sm-12 col-xs-12">
					<% @display = user_signed_in? && (@group.members.include?(current_user) || @group.user_id == current_user.id) %>
				<% if @post && @display %>
			      <div id="addPostArea">
						<%= form_for @post, url: group_posts_path(params[:id]), remote: true, html: { id: 'formAddPost' } do |f| %>
							<div class="input textarea">
								<%= f.text_area :text, placeholder: "What's New... ?", class: 'makeHigherTextarea'  %>
							</div>
							<div class="clearfix"></div>
							<div class="formAddPostSubmit">
								<div class="submit">
									<%= button_tag "Post", class: "btn btn-primary", 'data-disable-with' => "<i class='fa fa-spinner fa-spin'></i>".html_safe %>
                  
								</div>
							</div>
						<% end %>
					</div>
				<% end %>
				</div>
			</div>
			<div class="row">
		  	<div class="col-md-12 col-sm-12 col-xs-12">
			    <div id="postsList">
			      <%= render :partial => 'group_posts/post', :collection => @posts, :as => :post, :locals => {:group => @group} %>
			      <% if @posts.blank? %>
							<span>This group doesn't have any posts yet.</span>
						<% else %>
							<div id='more-posts'>
				        <div class="morePostsButton">
				          <%= link_to 'MORE', '', :remote => true, :'data-no-turbolink' => true %>
				        </div>
				      </div>
						<% end %>
			      <div style="clear:both"></div>
			    </div>
				</div>
				<div style="clear:both"></div>
			</div>
	  </div>
	</div>

	<div class="col-md-4 col-sm-4 col-xs-12">
		<div class="groupProfilePhoto">
			<%= link_to group_path(@group.url) do %>
				<%= image_tag @group._photo(:middle), :class => "img-responsive", :onError => "this.onerror=null;this.src='/group.png';", :style => "margin: 0 auto;" %>
			<% end %>
		</div>
		<div class="groupProfileText">
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-primary">
					  <div class="panel-heading">
					    <h3 class="panel-title">Description</h3>
					  </div>
					  <div class="panel-body">
					  	<%= @group.about %>
							<div style="clear:both"></div>
					  </div>
					</div>
				</div>
				<div class="col-md-12">
					<div class="panel panel-primary">
					  <div class="panel-heading">
					    <h3 class="panel-title">About</h3>
					  </div>
					  <div class="panel-body">
					  	<%= @group.long_about %>
							<div style="clear:both"></div>
					  </div>
					</div>
				</div>
			</div>
			<div class="row moderatorTitle"> 
				<div class="col-md-12">
					<div class="panel panel-primary">
					  <div class="panel-heading">
					    <h3 class="panel-title">Moderator</h3>
					  </div>
					  <div class="panel-body">
					  	<div class="col-md-4 col-sm-4 col-xs-12 moderatorPhoto"> 
								<%= link_to profile_path(@group.owner) do %>
					        <%= image_tag @group.owner.photo(:thumb), :class => "img-responsive", :style => "margin: 0 auto;" %>
					      <% end %>
							</div>
							<div class="col-md-8 col-sm-8 col-xs-12 moderatorText">
								<%= link_to @group.owner.title, profile_path(@group.owner) %>
								<br><%= @group.owner.profile.summary %>
							</div>
							<div style="clear:both"></div>
					  </div>
					</div>
				</div>
			</div>
			<div style="padding-top:10px; font-size:14px;">
				<% if current_user.present? %>
                  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#suggestFriend">Suggest to Friends</button><br><br>
                <% end %>
                <i class="fa fa-clock-o"></i> 
				Last action in group 
				<% if @group.last_action_at > Time.now - 2.months.to_i %>
					<%= time_ago_in_words(@group.last_action_at) %> ago
				<% else %>
					more than 2 months ago 
				<% end %>        
			</div>
      
		</div>

	</div>
</div>



<% if current_user.present? %>
  <!-- Suggest to Friends Modal -->
  <div class="modal fade suggestfriend" id="suggestFriend" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <%#= form_tag(controller: "groups#suggest_to_friend", action: "suggest_to_friend", method: "post") do %>
      <%#= form_tag({controller: "groups", action: "suggest_to_friend"}, method: "post") do %>
      <%= form_for @group, :url => suggest_to_friend_group_path(@group) , :html => { :method => "post" } do |f| %>
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Suggest to Friends</h4>
        </div>
        <div class="modal-body" style="height:300px; overflow-y: auto;">
          
            <% @already_members.each do |friend| %>
              <div class="col-md-12 col-sm-12 col-xs-12 padItemTab">
                <div class="col-md-3 col-sm-6 col-xs-6 padItemTabPhoto">
                  <%= link_to profile_path(friend) do %>
                    <%= image_tag friend._photo(:thumb), :class => "img-responsive", :style => "margin: 0 auto;" %>
                  <% end %>
                </div>

                <div class="col-md-9 col-sm-6 col-xs-6 padItemTabText">
                  <div class="row padItemTabTitle">
                    <div class="padItemTabLeft">
                      <%= link_to truncate(friend.title, :length => 15, :omission => '..'), profile_path(friend) %>
                    </div>
                    <div class="padItemTabRight">
                      <%#= link_to "Suggest", suggest_to_friend_group_path(@group.id, friend.id), :method => 'post' ,:class => "btn btn-xs btn-primary" %>
                       <%= check_box_tag "user_ids[]", friend.id %>
                    </div>
                  </div>
                  <div style="clear:both"></div>
                  <%#= truncate starter.profile.summary, :length => 25, :omission => '...' %>
                </div>
              </div>
              <div style="clear:both"></div>
            <% end %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Suggest", :class => "btn btn-primary" %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
        </div>
      </div>
      <% end %>
    </div>
  </div>
<% end %>